name: Build Binaries

on:
  push:
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

env:
  CGO_ENABLED: 0
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  REPO: ghcr.io/sharecare/traefik
  VERSION: latest

jobs:

  build-webui:
    uses: ./.github/workflows/template-webui.yaml

  build-binary:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
    needs:
      - build-webui

    steps:
      - name: Check out code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        env:
          ImageOS: ${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.goarm }}
        with:
          go-version-file: '.go-version'
          check-latest: true

      - name: Artifact webui
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: webui.tar.gz

      - name: Untar webui
        run: |
          tar xvf webui.tar.gz
          rm webui.tar.gz

      - name: Set version
        run: echo "VERSION=${GITHUB_REF#refs/*/}-AL" >> $GITHUB_ENV

      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          GOARM: ${{ matrix.goarm }}
        run: make binary

      - name: Tar binary
        run: |
          tar czvf traefik-binary.tar.gz ./dist

      - name: Artifact binary
        uses: actions/upload-artifact@v4
        with:
          name: traefik-binary.tar.gz
          path: traefik-binary.tar.gz

  build-docker:
    runs-on: ubuntu-latest
    needs:
      - build-binary
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Set version
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Artifact binary
        uses: actions/download-artifact@v4
        with:
          name: traefik-binary.tar.gz

      - name: Untar binary
        run: tar xvf traefik-binary.tar.gz

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build . --tag ${{ env.REPO }}:${{ env.VERSION }}
          docker push ${{ env.REPO }}:${{ env.VERSION }}
