name: Build Binaries

on:
  push:
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

env:
  GO_VERSION: '1.22'
  CGO_ENABLED: 0
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  REPO: ghcr.io/sharecare/traefik
  VERSION: latest

jobs:

  build-webui:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build webui
        run: |
          make clean-webui generate-webui
          tar czvf webui.tar.gz ./webui/static/

      - name: Artifact webui
        uses: actions/upload-artifact@v4
        with:
          name: webui.tar.gz
          path: webui.tar.gz

  build-binary:
    runs-on: ubuntu-22.04
    needs:
      - build-webui

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Artifact webui
        uses: actions/download-artifact@v4
        with:
          name: webui.tar.gz

      - name: Untar webui
        run: tar xvf webui.tar.gz

      - name: Set version
        run: echo "VERSION=${GITHUB_REF#refs/*/}-PL" >> $GITHUB_ENV

      - name: Build
        run: make binary

      - name: Tar binary
        run: |
          tar czvf traefik-binary.tar.gz ./dist

      - name: Artifact binary
        uses: actions/upload-artifact@v4
        with:
          name: traefik-binary.tar.gz
          path: traefik-binary.tar.gz

  build-docker:
    runs-on: ubuntu-22.04
    needs:
      - build-binary
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Set version
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Artifact binary
        uses: actions/download-artifact@v4
        with:
          name: traefik-binary.tar.gz

      - name: Untar binary
        run: tar xvf traefik-binary.tar.gz

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build . --tag ${{ env.REPO }}:${{ env.VERSION }}
          docker push ${{ env.REPO }}:${{ env.VERSION }}
